name: asdf_test
channels:
  - defaults
  - anaconda
  - conda-forge
dependencies:
  - python=3.8
  - semantic_version>=2.8
  - pyyaml>=3.10
  - jsonschema>=3.0.2,<4
  - numpy>=1.10
  - importlib_resources>=3
  - packaging>=16.0
  - pytest
  - astropy
  - pytest-astropy